# Generated by Django 4.0.3 on 2022-03-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_ownder_game_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='track_health',
            field=models.BooleanField(default=True),
        ),
    ]
