# Generated by Django 4.0.3 on 2022-03-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(to='core.player'),
        ),
        migrations.AddField(
            model_name='player',
            name='character_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='health',
            field=models.IntegerField(default=4),
        ),
    ]
