# Generated by Django 4.0.3 on 2022-03-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_player_game_game_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='character_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
